spring:
  application:
    name: "Cogmaster"

server:
  port: 2137

cogmaster:
  properties:
    path: "properties"

  routers:
    path: "routers"

  parsers:
    path: "parseable"
    list:
      - "item"
      - "harness"
      - "effect"
      - "conversation"
      - "attack"
      - "actor"
      - "accessory"
